# Generated by Django 4.0.4 on 2022-05-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='cidudad',
            new_name='ciudad',
        ),
    ]
